common:
  accounts:
    sandbox:
      email: sandbox@example.com
      number: '123456789012'
      roles:
        RolePlatformReadOnly:
        - platform_member
  groups:
  - platform_member
  ssh_bucket_name: user-sync
  ssh_keys:
    humpty.dumpty: ssh-ed25519 humptyDumpty
    john.doe: ssh-ed25519 johnDoe
  users:
    andy.test01:
    - platform_member
    ash.testone:
    - platform_member
    ash.testthree:
    - platform_member
    ash.testtwo:
    - platform_member
    humpty.dumpty:
    - platform_member
    john.doe:
    - platform_member
    test.user:
    - platform_member
production:
  resource_prefix: ''
testing:
  resource_prefix: ''
