common:
  accounts:
    sandbox:
      email: sandbox@example.com
      number: '123456789012'
      roles:
        RolePlatformReadOnly:
        - platform_member
  groups:
  - platform_member
  ssh_bucket_name: user-sync
  ssh_keys:
    humpty.dumpty: ssh-ed25519 humptyDumpty
    john.doe: ssh-ed25519 johnDoe
  users:
    daniel.cashcow:
    - platform_member
    dod3427.snsalltest:
    - platform_member
    humpty.dumpty:
    - platform_member
    john.doe:
    - platform_member
    test.user:
    - platform_member
production:
  resource_prefix: ''
testing:
  resource_prefix: ''
